blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('users/', include('users.urls', namespace='users'))

    ]

learning_logs/urls.py
"""
定义learning_logs的URL模式
"""
from . import views
from django.urls import path

app_name = 'learning_logs'

urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    # 特定主题的详细页面
    path(r"topics/<int:topic_id>/", views.topic, name='topic'),
    # 用于添加新主题的网页
    path('new_topic', views.new_topic, name='new_topic'),
    # 用于添加新笔记的页面
    path(r'new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # 用于编辑笔记的页面
    path(r"edit_entry/<int:entry_id>/", views.edit_entry, name='edit_entry'),

]

users/urls.py
"""定义应用users的URL模式"""

from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'
LoginView.template_name = 'users/login.html'
urlpatterns = [
    # 登录界面
    path('login/', LoginView.as_view(), name='login'),
    # 注销
    path('logout/', views.logout_view, name='logout'),
    # 注册
    path('register/', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):
    """学习的主题"""
    text = models.CharField(max_length=200)
    date_add = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """"学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """"返回模型的字符串表示"""
        if len(self.text) >= 50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic,Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    """网页的主页"""
    return render(request, 'learning_logs/index.html')


@login_required()
def topics(request):
    """显示当前登录用户所拥有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_add')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required()
def topic(request, topic_id):
    """显示单个主题及其所有条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认主题属于当前用户
    if topic.owner != request.user:
        return Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required()
def new_topic(request):
    """添加新的主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新的表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required()
def new_entry(request, topic_id):
    """在特定的主题下添加笔记"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        return Http404
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required()
def edit_entry(request, entry_id):
    """编辑现有的笔记"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        return Http404
    if request.method != 'POST':
        # 初次请求使用当前笔记填充表单
        form = EntryForm(instance=entry)
    else:
        # 对POST请求提交的数据进行出来
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 出来填好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Copatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
  <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">

      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">

          </button>
          <a class="navbar-brand" href="{% url "learning_logs:index" %}">
               学习笔记</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav ">
          <li><a href="{% url "learning_logs:topics" %}">主题</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>您好，{{ user.username }} !</a></li>
            <li><a href="{% url 'users:logout' %}">注销</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">注册</a></li>
              <li><a href="{% url 'users:login' %}">登录</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->

    </div>
  </nav>

  <div class="container">

    <div class="page-header">
      {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
  </div><!-- /container -->
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{%  load bootstrap3%}
{% block header %}
    <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock %}

{% block content %}

    <h4>编辑：</h4>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="提交" class="btn btn-primary">保存</button>
      {% endbuttons %}
    </form>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <div class="jumbotron">
     <h1>你的学习足迹</h1>
    </div>
{% endblock header %}
{% block content %}
    <h2>
    <a href="{% url 'users:register' %}">注册账户</a>建立属于自己的学习笔记，记录自己所学习过的主题。
    </h2>
    <h2>
    无论何时学习到关于某个主题的新内容，创建一个笔记来记录它
    </h2>
{% endblock %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock %}

{% block content %}


    <h3>添加一条新笔记：</h3>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
      <button name="提交" class="btn btn-primary">添加</button>
      {% endbuttons %}
    </form>

{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>添加一个新主题：</h2>
{% endblock %}

{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="提交" class="btn btn-primary">添加</button>
      {% endbuttons %}
    </form>


{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock %}

{% block content %}
    <p>
      <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新笔记</a>
    </p>

    <ul>
    {% for entry in entries %}
      <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
              {{ entry.date_added| date:"Y/m/d H:i" }}
              <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑</a>
              </small>
            </h3>
        </div>
        <div class="panel-body">
            {{ entry.text|linebreaks }}
        </div>
      </div> <!-- panel -->
    {% empty %}
      <li>
      这个主题下还没有记录笔记
      </li>
    {% endfor %}
    </ul>

{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
  <h1>主题</h1>
{% endblock %}

{% block content %}

  <ul>
    {% for topic in topics %}
        <li>
            <h3>
              <a href="{% url "learning_logs:topic" topic.id %}">{{ topic }}</a>
            </h3>
        </li>
    {% empty %}
      <li>还未添加学习主题</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">添加新主题</a></h3>

{% endblock %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>登录</h2>
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="提交" class="btn btn-primary">确定</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="提交">注册</button>
    <input type="hidden" name="next" value="{% url "learning_logs:index" %}"/>

    </form>

{% endblock %}